using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using Trident.CodeGeneration.Shared;
using Trident.CodeGeneration.Decoding;
using Trident.CodeGeneration.Attributes;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Trident.CodeGeneration.CodeGen
{
    [Generator]
    public class ARMGeneratorEntryPoint : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var methodCandidates = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Trident.Core.CPU.Decoding.ARM.ARMParameterAttribute`1",
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol)
                .Select((method, _) =>
                {
                    var hasGroupAttr = method.GetAttributes()
                        .Any(attr => attr.AttributeClass?.ToDisplayString() == "Trident.Core.CPU.Decoding.ARM.ARMGroupAttribute");

                    return hasGroupAttr ? method : null;
                })
                .Where(static method => method is not null)
                .Collect();

            context.RegisterSourceOutput(methodCandidates, EmitARMSource);
        }


        private static void EmitARMSource(SourceProductionContext spc, ImmutableArray<IMethodSymbol> methods)
        {
            var methodContracts = new Dictionary<string, (IMethodSymbol Method, StringBuilder Builder)>();
            StringBuilder tableBuilder = new(@"// <auto-generated/>
namespace Trident.Core.CPU.Decoding.ARM
{
    internal partial class ARMDispatcher<TBus> where TBus : struct, Trident.Core.Bus.IDataBus
    {
        private void InitGeneratedHandlers()
        {
");

            HashSet<string> emittedStructs = [];
            Dictionary<ARMGroup, IMethodSymbol> groupMethodCache = [];

            foreach (var methodSymbol in methods)
            {
                StringBuilder contractBuilder = new();
                contractBuilder.AppendLine(ARMInterfaceGenerator.Generate(methodSymbol));
                methodContracts[methodSymbol.Name] = (methodSymbol, contractBuilder);
            }

            for (uint opcode = 0; opcode < 4096; opcode++)
            {
                uint expandedOpcode = (opcode & 0xFF0) << 16 | (opcode & 0x00F) << 4;
                ARMGroup group = ARMDecoder.DetermineARMGroup(expandedOpcode);

                if (!groupMethodCache.TryGetValue(group, out var method))
                {
                    method = ARMDecoder.FindGroupMethod(methods, group);
                    groupMethodCache[group] = method;
                }

                if (method is null)
                    continue;

                var values = TraitDecoder.DecodeTraitValues(expandedOpcode, method);
                string structName = ARMTraitStructGenerator.GetPermutationKey(method, values);
                tableBuilder.AppendLine($"            _instructionHandlers[0x{opcode:X}] = _cpu.{method.Name}<{structName}>;");

                if (!emittedStructs.Add(structName))
                    continue;

                string structBody = ARMTraitStructGenerator.GenerateTraitStruct(
                    structName, method.Name, ARMAttributeParser.Parse(method), values);

                methodContracts[method.Name].Builder.AppendLine(structBody);
            }

            foreach (var kvp in methodContracts)
            {
                string methodName = kvp.Key;
                StringBuilder builder = kvp.Value.Builder;

                spc.AddSource($"{methodName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
            }

            tableBuilder.AppendLine("        }\n    }\n}");
            spc.AddSource("ARMDispatcher.g.cs", SourceText.From(tableBuilder.ToString(), Encoding.UTF8));
        }
    }
}