using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Runtime.CompilerServices;

namespace Trident.CodeGeneration.CodeGen
{
    public static class CodeGenUtils
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static uint GetBit(this uint value, int bit) => value >> bit & 1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static bool IsBitSet(this uint value, int bit) => (value >> bit & 1) != 0;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static uint Extract(this uint value, int hi, int lo) =>
            value >> lo & (1u << hi - lo + 1) - 1;


        internal const string GenericParameterAttributeName = "Trident.Core.CPU.Decoding.TemplateParameterAttribute`1";
        internal const string GroupAttributeName = "Trident.Core.CPU.Decoding.TemplateGroupAttribute";


        internal static void GenerateDispatcherInitializer(SourceProductionContext spc, ImmutableArray<string> methodNames, bool isARM)
        {
            var centralBuilder = new StringBuilder();
            centralBuilder.AppendLine($@"// <auto-generated/>
namespace Trident.Core.CPU.Decoding.{(isARM ? "ARM" : "Thumb")}
{{
    internal partial class {(isARM ? "ARM" : "Thumb")}Dispatcher<TBus> where TBus : struct, Trident.Core.Bus.IDataBus
    {{
        private void InitGeneratedHandlers()
        {{");

            foreach (var name in methodNames)
                centralBuilder.AppendLine($"            InitGeneratedHandler_{name}();");

            centralBuilder.AppendLine("        }\n    }\n}");
            spc.AddSource($"{(isARM ? "ARM" : "Thumb")}Dispatcher.g.cs", SourceText.From(centralBuilder.ToString(), Encoding.UTF8));
        }
    }
}
