using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using Trident.CodeGeneration.Shared;
using Trident.CodeGeneration.Decoding;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Trident.CodeGeneration.CodeGen.Metadata;

namespace Trident.CodeGeneration.CodeGen
{
    [Generator]
    public class OpcodeTemplateGenerator : IIncrementalGenerator
    {
        private static readonly Dictionary<ARMGroup, List<uint>> _armGroupToOpcodes = ARMDecoder.BuildGroupOpcodeMap();

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var methodCandidates = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    CodeGenUtils.GenericParameterAttributeName,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) => new TemplateMethodInfo((IMethodSymbol)ctx.TargetSymbol));
                //.Where(static info => info.Group != null);

            context.RegisterSourceOutput(methodCandidates, GenerateSourceForMethod);

            // Write both global initializers
            var armMethods = methodCandidates
                .Where(static info => info.IsARM)
                .Select((info, _) => info.Name)
                .Collect();

            var thumbMethods = methodCandidates
                .Where(static info => !info.IsARM)
                .Select((info, _) => info.Name)
                .Collect();

            context.RegisterSourceOutput(armMethods, (spc, names) =>
            {
                CodeGenUtils.GenerateDispatcherInitializer(spc, names, isARM: true);
            });

            context.RegisterSourceOutput(thumbMethods, (spc, names) =>
            {
                CodeGenUtils.GenerateDispatcherInitializer(spc, names, isARM: false);
            });
        }

        private static void GenerateSourceForMethod(SourceProductionContext spc, TemplateMethodInfo info)
        {
            string sourceText = GenerateSourceFor(info);
            spc.AddSource($"{info.Name}.g.cs", sourceText);
        }

        private static string GenerateSourceFor(TemplateMethodInfo info)
        {
            HashSet<string> emittedStructs = [];
            StringBuilder structBuilder = new();
            string targetNamespace = $"Trident.Core.CPU.Decoding.{(info.IsARM ? "ARM" : "Thumb")}";
            string targetDispatcher = $"{(info.IsARM ? "ARM" : "Thumb")}Dispatcher";

            StringBuilder builder = new($@"// <auto-generated/>
namespace {targetNamespace}
{{
    internal partial class {targetDispatcher}<TBus> where TBus : struct, Trident.Core.Bus.IDataBus
    {{
        private void InitGeneratedHandler_{info.Name}()
        {{
");

            if (!_armGroupToOpcodes.TryGetValue((ARMGroup)info.Group!.Value, out var opcodes))
                opcodes = new List<uint>();

            // TODO: Generate proper thumb opcode tables and stuff
            foreach (uint expandedOpcode in opcodes)
            {
                var values = TraitDecoder.DecodeTraitValues(expandedOpcode, info.Traits);
                string structName = TraitStructGenerator.GetPermutationKey(info.Name, values);
                builder.AppendLine(
                    $"            _instructionHandlers[0x{((expandedOpcode >> 16) & 0xFF0) | ((expandedOpcode >> 4) & 0x00F):X}]" +
                    $" = _cpu.{info.Name}<{structName}>;"
                );

                if (emittedStructs.Add(structName))
                {
                    string structBody = TraitStructGenerator.GenerateTraitStruct(structName, info.Name, info.Traits, values);
                    structBuilder.AppendLine(structBody);
                }
            }

            builder.AppendLine("        }\n    }\n");
            builder.AppendLine(TemplateContractGenerator.Generate(info.Name, info.Traits));
            builder.Append(structBuilder.ToString());
            builder.Append("}");

            return builder.ToString();
        }
    }
}