using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using Trident.CodeGeneration.Shared;
using Trident.CodeGeneration.Decoding;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Trident.CodeGeneration.CodeGen.Metadata;

namespace Trident.CodeGeneration.CodeGen
{
    [Generator]
    public class OpcodeTemplateGenerator : IIncrementalGenerator
    {
        private static readonly Dictionary<ARMGroup, List<uint>> _armGroupToOpcodes = ARMDecoder.BuildGroupOpcodeMap();
        private static readonly Dictionary<ThumbGroup, List<uint>> _thumbGroupToOpcodes = ThumbDecoder.BuildGroupOpcodeMap();

        private static readonly Func<uint, uint> _compressARMOpcode = expandedOpcode =>
            ((expandedOpcode >> 16) & 0xFF0) | ((expandedOpcode >> 4) & 0x00F);

        private static readonly Func<uint, uint> _compressThumbOpcode = expandedOpcode =>
            ((expandedOpcode >> 6));


        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var methodCandidates = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    CodeGenUtils.GroupAttributeName,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) => new TemplateMethodInfo((IMethodSymbol)ctx.TargetSymbol));

            context.RegisterSourceOutput(methodCandidates, GenerateSourceForMethod);

            // Write both global initializers
            var armMethods = methodCandidates
                .Where(static info => info.IsARM)
                .Select((info, _) => info.Name)
                .Collect();

            var thumbMethods = methodCandidates
                .Where(static info => !info.IsARM)
                .Select((info, _) => info.Name)
                .Collect();

            context.RegisterSourceOutput(armMethods, (spc, names) =>
            {
                CodeGenUtils.GenerateDispatcherInitializer(spc, names, isARM: true);
            });

            context.RegisterSourceOutput(thumbMethods, (spc, names) =>
            {
                CodeGenUtils.GenerateDispatcherInitializer(spc, names, isARM: false);
            });
        }


        private static void GenerateSourceForMethod(SourceProductionContext spc, TemplateMethodInfo info)
        {
            HashSet<string> emittedStructs = [];
            StringBuilder structBuilder = new();
            string targetNamespace = $"Trident.Core.CPU.Decoding.{(info.IsARM ? "ARM" : "Thumb")}";
            string targetDispatcher = $"{(info.IsARM ? "ARM" : "Thumb")}Dispatcher";
            bool hasTraits = info.Traits.Count() > 0;

            StringBuilder builder = new($@"// <auto-generated/>
namespace {targetNamespace}
{{
    internal partial class {targetDispatcher}<TBus> where TBus : struct, Trident.Core.Bus.IDataBus
    {{
        private void InitGeneratedHandler_{info.Name}()
        {{
");


            List<uint> opcodes = [];

            if (info.IsARM)
            {
                if (!_armGroupToOpcodes.TryGetValue((ARMGroup)info.Group!.Value, out opcodes))
                    opcodes = new List<uint>();
            }
            else
            {
                if (!_thumbGroupToOpcodes.TryGetValue((ThumbGroup)info.Group!.Value, out opcodes))
                    opcodes = new List<uint>();
            }

            foreach (uint expandedOpcode in opcodes)
            {
                uint compressedOpcode = info.IsARM ? _compressARMOpcode(expandedOpcode) : _compressThumbOpcode(expandedOpcode);
                var values = TraitDecoder.DecodeTraitValues(expandedOpcode, info.Traits);

                if (hasTraits)
                {
                    string structName = TraitStructGenerator.GetPermutationKey(info.Name, values);

                    builder.AppendLine(
                        $"            _instructionHandlers[0x{compressedOpcode:X3}]" +
                        $" = _cpu.{info.Name}<{structName}>;"
                    );

                    if (emittedStructs.Add(structName))
                    {
                        string structBody = TraitStructGenerator.GenerateTraitStruct(structName, info.Name, info.Traits, values);
                        structBuilder.AppendLine(structBody);
                    }
                }
                else
                {
                    builder.AppendLine(
                        $"            _instructionHandlers[0x{compressedOpcode:X3}]" +
                        $" = _cpu.{info.Name};"
                    );
                }
            }

            builder.AppendLine("        }\n    }\n");

            if (hasTraits)
                builder.AppendLine(TemplateContractGenerator.Generate(info.Name, info.Traits));

            builder.Append(structBuilder.ToString());
            builder.Append("}");

            spc.AddSource($"{info.Name}.g.cs", builder.ToString());
        }
    }
}