namespace Trident.Tests.SingleStep.Infrastructure;

internal static class TestTypeResolver
{
    internal enum TestType
    {
        ArmBx,
        ArmBBl,
        ArmCdp,
        ArmDataProcImmediate,
        ArmDataProcImmediateShift,
        ArmDataProcRegisterShift,
        ArmLdmStm,
        ArmLdrhStrh,
        ArmLdrsbLdrsh,
        ArmLdrStrImmediateOffset,
        ArmLdrStrRegisterOffset,
        ArmMcrMrc,
        ArmMrs,
        ArmMsrImm,
        ArmMsrReg,
        ArmMullMlal,
        ArmMulMla,
        ArmStcLdc,
        ArmSwi,
        ArmSwp,
        ThumbAddCmpMovHi,
        ThumbAddSpOrPc,
        ThumbAddSub,
        ThumbAddSubSp,
        ThumbB,
        ThumbBcc,
        ThumbBlBlxPrefix,
        ThumbBlSuffix,
        ThumbBx,
        ThumbDataProc,
        ThumbLdmStm,
        ThumbLdrbStrbImmOffset,
        ThumbLdrhStrhImmOffset,
        ThumbLdrhStrhRegOffset,
        ThumbLdrsbStrbRegOffset,
        ThumbLdrshLdrsbRegOffset,
        ThumbLdrPcRel,
        ThumbLdrStrImmOffset,
        ThumbLdrStrRegOffset,
        ThumbLdrStrSpRel,
        ThumbLslLsrAsr,
        ThumbMovCmpAddSub,
        ThumbPushPop,
        ThumbSwi,
        ThumbUndefinedBcc
    }


    internal static TestType GetTestType(string filePath)
    {
        string fileName = Path.GetFileNameWithoutExtension(filePath).ToLowerInvariant();

        return fileName switch
        {
            "arm_bx" => TestType.ArmBx,
            "arm_b_bl" => TestType.ArmBBl,
            "arm_cdp" => TestType.ArmCdp,
            "arm_data_proc_immediate" => TestType.ArmDataProcImmediate,
            "arm_data_proc_immediate_shift" => TestType.ArmDataProcImmediateShift,
            "arm_data_proc_register_shift" => TestType.ArmDataProcRegisterShift,
            "arm_ldm_stm" => TestType.ArmLdmStm,
            "arm_ldrh_strh" => TestType.ArmLdrhStrh,
            "arm_ldrsb_ldrsh" => TestType.ArmLdrsbLdrsh,
            "arm_ldr_str_immediate_offset" => TestType.ArmLdrStrImmediateOffset,
            "arm_ldr_str_register_offset" => TestType.ArmLdrStrRegisterOffset,
            "arm_mcr_mrc" => TestType.ArmMcrMrc,
            "arm_mrs" => TestType.ArmMrs,
            "arm_msr_imm" => TestType.ArmMsrImm,
            "arm_msr_reg" => TestType.ArmMsrReg,
            "arm_mull_mlal" => TestType.ArmMullMlal,
            "arm_mul_mla" => TestType.ArmMulMla,
            "arm_stc_ldc" => TestType.ArmStcLdc,
            "arm_swi" => TestType.ArmSwi,
            "arm_swp" => TestType.ArmSwp,
            "thumb_add_cmp_mov_hi" => TestType.ThumbAddCmpMovHi,
            "thumb_add_sp_or_pc" => TestType.ThumbAddSpOrPc,
            "thumb_add_sub" => TestType.ThumbAddSub,
            "thumb_add_sub_sp" => TestType.ThumbAddSubSp,
            "thumb_b" => TestType.ThumbB,
            "thumb_bcc" => TestType.ThumbBcc,
            "thumb_bl_blx_prefix" => TestType.ThumbBlBlxPrefix,
            "thumb_bl_suffix" => TestType.ThumbBlSuffix,
            "thumb_bx" => TestType.ThumbBx,
            "thumb_data_proc" => TestType.ThumbDataProc,
            "thumb_ldm_stm" => TestType.ThumbLdmStm,
            "thumb_ldrb_strb_imm_offset" => TestType.ThumbLdrbStrbImmOffset,
            "thumb_ldrh_strh_imm_offset" => TestType.ThumbLdrhStrhImmOffset,
            "thumb_ldrh_strh_reg_offset" => TestType.ThumbLdrhStrhRegOffset,
            "thumb_ldrsb_strb_reg_offset" => TestType.ThumbLdrsbStrbRegOffset,
            "thumb_ldrsh_ldrsb_reg_offset" => TestType.ThumbLdrshLdrsbRegOffset,
            "thumb_ldr_pc_rel" => TestType.ThumbLdrPcRel,
            "thumb_ldr_str_imm_offset" => TestType.ThumbLdrStrImmOffset,
            "thumb_ldr_str_reg_offset" => TestType.ThumbLdrStrRegOffset,
            "thumb_ldr_str_sp_rel" => TestType.ThumbLdrStrSpRel,
            "thumb_lsl_lsr_asr" => TestType.ThumbLslLsrAsr,
            "thumb_mov_cmp_add_sub" => TestType.ThumbMovCmpAddSub,
            "thumb_push_pop" => TestType.ThumbPushPop,
            "thumb_swi" => TestType.ThumbSwi,
            "thumb_undefined_bcc" => TestType.ThumbUndefinedBcc,
            _ => throw new ArgumentException($"Unknown test type for file: {filePath}")
        };
    }
}
